---

#native_stds: [0.5, 1, 2, 5, 10, 16, 32]
#down_sample_ratios: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

native_stds: [0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.5, 3, 3.5, 4]
down_sample_ratios: [1]
secondary_blur_vals: [0]