---

# Q = 0.75
num_samples: 2048
f_num: 7.5  # dimensionless
pix_pitch: 8  # microns
ff: 0.8  # dimensionless
wl: [0.5, 0.7, 0.9]  # microns

kernel_half_width: 15
num_kernels: 128

p_smear_range: [0.05, 0.15]
sigma_jitter_range: [0.05, 0.15]
wl_rms_range: [0.05, 0.25]
l_corr_range: [0.05, 0.2]
